version: '3'

services:
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin1234"
    ports:
      - "15432:5432"
    volumes:
      - C:/Users/emefsonfs/Documents/develop/projetos-backend/docker/PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "emersonfdasilva2@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin1234"
    ports:
      - "16543:80"
    depends_on:
      - teste-postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge